database_config:
  host: "127.0.0.1"
  user: "root"
  password: "matrix01M"
  database: "Group_5"

# dataset_paths:
#   dataset1: "datasets/amazon_prime_titles.csv"
#   dataset2: "datasets/disney_plus_titles.csv"
#   dataset3: "datasets\\netflix_titles.csv"
  # Add more datasets as required
