name: Python CI with MySQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7  # You can choose the version you need
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.8'

    - name: Create config.yml
      run: |
        cat > config.yml <<EOF
        database_config:
          host: ${{ secrets.DB_HOST }}
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          database: ${{ secrets.DB_NAME }}
        dataset_paths:
          dataset1: ${{ secrets.DATASET1_PATH }}
          dataset2: ${{ secrets.DATASET2_PATH }}
          dataset3: ${{ secrets.DATASET3_PATH }}
        EOF
            
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
          echo "Waiting for MySQL to be up..."
          sleep 5
        done

    - name: Run tests
      run: |
        # Add your testing commands here
        pytest

    - name: Convert Notebooks to Python script
      run: |
        jupyter nbconvert --to script *.ipynb

    - name: Execute converted Python scripts
      run: |
        for script in *.py; do
          python "$script"
        done

    # # Use the MYSQL environment variables as needed in your scripts or tests
    # env:
    #   MYSQL_HOST: 127.0.0.1
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: password
    #   MYSQL_DB: Group_5
